# Generated by Django 3.2.7 on 2021-10-02 16:34

import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='clicks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='RUB', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
